Adjust Unity build targets
Co-authored-by: lask3802 <5467042+lask3802@users.noreply.github.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -31,7 +31,7 @@ jobs:
           - targetPlatform: iOS
             buildTarget: iOS
           - targetPlatform: StandaloneOSX
-            buildTarget: OSXUniversal
+            buildTarget: StandaloneOSX
           # Not yet supported GitHub actions:
           # - Android # Build a Android standalone.
           # - PS4 # Build a Playstation 4 standalone.
@@ -108,7 +108,7 @@ jobs:
       
       - name: MSBuild (macOS)
         working-directory: AssemblyBuild/Zenject-usage
-        run: msbuild Zenject-usage.sln
+        run: msbuild Zenject-usage.sln || { echo "MSBuild failed with exit code $?"; exit 1; }
 
       - name: Upload dll (macOS)
         uses: actions/upload-artifact@v4
